// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHaDrR4aBvJvKeoi9vtSFHu8PJcKtrZL4',
    appId: '1:534853045080:web:ea7d9ddcb67078d302332d',
    messagingSenderId: '534853045080',
    projectId: 'assets-9c861',
    authDomain: 'assets-9c861.firebaseapp.com',
    storageBucket: 'assets-9c861.firebasestorage.app',
    measurementId: 'G-79EG2YXLHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYTFtnYoRzfTwa1Ewnu-k9MjOAlJmlYUU',
    appId: '1:534853045080:android:32b1edee279577fb02332d',
    messagingSenderId: '534853045080',
    projectId: 'assets-9c861',
    storageBucket: 'assets-9c861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9fM8Bu-hRgzeykj-57kyQG034T86iNo',
    appId: '1:534853045080:ios:dfea4e5c5ef4dc3a02332d',
    messagingSenderId: '534853045080',
    projectId: 'assets-9c861',
    storageBucket: 'assets-9c861.firebasestorage.app',
    iosBundleId: 'com.example.assetsManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf9fM8Bu-hRgzeykj-57kyQG034T86iNo',
    appId: '1:534853045080:ios:dfea4e5c5ef4dc3a02332d',
    messagingSenderId: '534853045080',
    projectId: 'assets-9c861',
    storageBucket: 'assets-9c861.firebasestorage.app',
    iosBundleId: 'com.example.assetsManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHaDrR4aBvJvKeoi9vtSFHu8PJcKtrZL4',
    appId: '1:534853045080:web:4e37f123e7d3fd4302332d',
    messagingSenderId: '534853045080',
    projectId: 'assets-9c861',
    authDomain: 'assets-9c861.firebaseapp.com',
    storageBucket: 'assets-9c861.firebasestorage.app',
    measurementId: 'G-C3219GZBN0',
  );
}
